### PR TITLE
Add compatibility for GHC 9.2

### PR DESCRIPTION
**Pull request by fendor**
Also, ditch dependency on `ghc-api-compat` so that
`hiedb` can actually be published to Hackage.

Depends on https://github.com/haskell/haskell-language-server/pull/2003

### CODE REVIEW

**Comment by fendor** [comment]
oops, honestly forgot there are tests

**Comment by fendor** [comment]
ping @wz1000

**Comment by fendor** [comment]
cc @jneira, this is one of the patches that drops the `ghc-api-compat` dep.

**Comment by jneira** [comment]
@fendor nice! thanks, we have to use this version of hiedb in hls i suppose??

**Comment by fendor** [comment]
@jneira Yes, ghcide is yet to be upgraded,  I wanted to do that in one sweep with GHC 9.2 support, but I am waiting for https://github.com/alanz/ghc-exactprint/pull/101

**Pull request merged**
